apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-store
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6380
    - name: redisPassword
      value: ''
    - name: keyPrefix
      value: 'none'
